matchBlocks=acacia_log:is_trunk=true:axis=y birch_log:is_trunk=true:axis=y cherry_log:is_trunk=true:axis=y dark_oak_log:is_trunk=true:axis=y jungle_log:is_trunk=true:axis=y mangrove_log:is_trunk=true:axis=y oak_log:is_trunk=true:axis=y pale_oak_log:is_trunk=true:axis=y spruce_log:is_trunk=true:axis=y
method=overlay_ctm
tiles=0 1 <skip> 2 1 2 1 <skip> <skip> <skip> <skip> <skip> 0 1 <skip> 2 1 2 <skip> 2 <skip> <skip> <skip> <skip> 0 1 <skip> 2 1 <skip> 1 <skip> <skip> <skip> <skip> <skip> 0 1 <skip> 2 <skip> 2 <skip> 2 <skip> <skip> <skip>
faces=sides
connect=state
layer=translucent
