matchBlocks=acacia_log:is_trunk=true:axis=z birch_log:is_trunk=true:axis=z cherry_log:is_trunk=true:axis=z dark_oak_log:is_trunk=true:axis=z jungle_log:is_trunk=true:axis=z mangrove_log:is_trunk=true:axis=z oak_log:is_trunk=true:axis=z pale_oak_log:is_trunk=true:axis=z spruce_log:is_trunk=true:axis=z
method=overlay_ctm
tiles=0 1 <skip> 2 1 2 1 <skip> <skip> <skip> <skip> <skip> 0 1 <skip> 2 1 2 <skip> 2 <skip> <skip> <skip> <skip> 0 1 <skip> 2 1 <skip> 1 <skip> <skip> <skip> <skip> <skip> 0 1 <skip> 2 <skip> 2 <skip> 2 <skip> <skip> <skip>
faces=north south
connect=state
layer=translucent
