matchBlocks=regions_unexplored:eucalyptus_log:axis=x:sides=0010,0011,00rl regions_unexplored:pine_log:axis=x:sides=0010,0011,00rl:transition_block=true regions_unexplored:silver_birch_log:axis=x:sides=0010,0011,00rl:is_base=true
method=overlay_fixed
tiles=left_horizontal_alt
faces=north
connect=state
layer=translucent