matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0100,1100,rl00 regions_unexplored:pine_log:axis=y:sides=0100,1100,rl00:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0100,1100,rl00:is_base=true
method=overlay_fixed
tiles=left_alt
faces=south
connect=state
layer=translucent