matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=1000,1001,l00r regions_unexplored:pine_log:axis=y:sides=1000,1001,l00r:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=1000,1001,l00r:is_base=true
method=overlay_fixed
tiles=left_alt
faces=east
connect=state
layer=translucent