matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=1000,1100,rl00 regions_unexplored:pine_log:axis=y:sides=1000,1100,rl00:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=1000,1100,rl00:is_base=true
method=overlay_fixed
tiles=right_alt
faces=west
connect=state
layer=translucent