matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0010,0011,00rl regions_unexplored:pine_log:axis=y:sides=0010,0011,00rl:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0010,0011,00rl:is_base=true
method=overlay_fixed
tiles=right_alt
faces=east
connect=state
layer=translucent