matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0001,1001,l00r regions_unexplored:pine_log:axis=y:sides=0001,1001,l00r:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0001,1001,l00r:is_base=true
method=overlay_fixed
tiles=right_alt
faces=south
connect=state
layer=translucent