matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0100,0110,0rl0 regions_unexplored:pine_log:axis=y:sides=0100,0110,0rl0:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0100,0110,0rl0:is_base=true
method=overlay_fixed
tiles=right_alt
faces=north
connect=state
layer=translucent