matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0000,0100 regions_unexplored:pine_log:axis=y:sides=0000,0100:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0000,0100:is_base=true
method=overlay_fixed
tiles=small_alt
faces=west
connect=state
layer=translucent