matchBlocks=regions_unexplored:eucalyptus_log:axis=y:sides=0000,1000 regions_unexplored:pine_log:axis=y:sides=0000,1000:transition_block=true regions_unexplored:silver_birch_log:axis=y:sides=0000,1000:is_base=true
method=overlay_fixed
tiles=small_alt
faces=south
connect=state
layer=translucent