matchBlocks=regions_unexplored:eucalyptus_log:axis=z:sides=0010,0110,0rl0 regions_unexplored:pine_log:axis=z:sides=0010,0110,0rl0:transition_block=true regions_unexplored:silver_birch_log:axis=z:sides=0010,0110,0rl0:is_base=true
method=overlay_fixed
tiles=left_horizontal_alt
faces=west
connect=state
layer=translucent