matchBlocks=regions_unexplored:eucalyptus_log:axis=z:sides=0001,1001,l00r regions_unexplored:pine_log:axis=z:sides=0001,1001,l00r:transition_block=true regions_unexplored:silver_birch_log:axis=z:sides=0001,1001,l00r:is_base=true
method=overlay_fixed
tiles=right_alt
faces=north
connect=state
layer=translucent