matchBlocks=regions_unexplored:eucalyptus_log:axis=z:sides=0000,0010 regions_unexplored:pine_log:axis=z:sides=0000,0010:transition_block=true regions_unexplored:silver_birch_log:axis=z:sides=0000,0010:is_base=true
method=overlay_fixed
tiles=small_alt
faces=south
connect=state
layer=translucent