matchBlocks=acacia_log:is_trunk=false:axis=y birch_log:is_trunk=false:axis=y cherry_log:is_trunk=false:axis=y dark_oak_log:is_trunk=false:axis=y jungle_log:is_trunk=false:axis=y mangrove_log:is_trunk=false:axis=y oak_log:is_trunk=false:axis=y pale_oak_log:is_trunk=false:axis=y spruce_log:is_trunk=false:axis=y stripped_acacia_log:is_trunk=false:axis=y stripped_birch_log:is_trunk=false:axis=y stripped_cherry_log:is_trunk=false:axis=y stripped_dark_oak_log:is_trunk=false:axis=y stripped_jungle_log:is_trunk=false:axis=y stripped_mangrove_log:is_trunk=false:axis=y stripped_oak_log:is_trunk=false:axis=y stripped_pale_oak_log:is_trunk=false:axis=y stripped_spruce_log:is_trunk=false:axis=y
method=overlay_fixed
tiles=edges
faces=sides
connect=state
layer=translucent
