matchBlocks=acacia_log:is_trunk=true:axis=x birch_log:is_trunk=true:axis=x cherry_log:is_trunk=true:axis=x dark_oak_log:is_trunk=true:axis=x jungle_log:is_trunk=true:axis=x mangrove_log:is_trunk=true:axis=x oak_log:is_trunk=true:axis=x pale_oak_log:is_trunk=true:axis=x spruce_log:is_trunk=true:axis=x
method=overlay_ctm
tiles=0 0 0 0 1 1 <skip> 1 <skip> <skip> <skip> <skip> 1 1 1 1 2 2 2 <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> 1 <skip> 1 <skip> <skip> <skip> <skip> 2 2 2 2 2 <skip> 2 <skip> <skip> <skip> <skip>
faces=sides
connect=state
layer=translucent
