matchBlocks=acacia_log:is_trunk=false:axis=x birch_log:is_trunk=false:axis=x cherry_log:is_trunk=false:axis=x dark_oak_log:is_trunk=false:axis=x jungle_log:is_trunk=false:axis=x mangrove_log:is_trunk=false:axis=x oak_log:is_trunk=false:axis=x pale_oak_log:is_trunk=false:axis=x spruce_log:is_trunk=false:axis=x stripped_acacia_log:is_trunk=false:axis=x stripped_birch_log:is_trunk=false:axis=x stripped_cherry_log:is_trunk=false:axis=x stripped_dark_oak_log:is_trunk=false:axis=x stripped_jungle_log:is_trunk=false:axis=x stripped_mangrove_log:is_trunk=false:axis=x stripped_oak_log:is_trunk=false:axis=x stripped_pale_oak_log:is_trunk=false:axis=x stripped_spruce_log:is_trunk=false:axis=x
method=overlay_fixed
tiles=edges
faces=sides
connect=state
layer=translucent
