matchBlocks=acacia_log:is_trunk=false:axis=z birch_log:is_trunk=false:axis=z cherry_log:is_trunk=false:axis=z dark_oak_log:is_trunk=false:axis=z jungle_log:is_trunk=false:axis=z mangrove_log:is_trunk=false:axis=z oak_log:is_trunk=false:axis=z pale_oak_log:is_trunk=false:axis=z spruce_log:is_trunk=false:axis=z stripped_acacia_log:is_trunk=false:axis=z stripped_birch_log:is_trunk=false:axis=z stripped_cherry_log:is_trunk=false:axis=z stripped_dark_oak_log:is_trunk=false:axis=z stripped_jungle_log:is_trunk=false:axis=z stripped_mangrove_log:is_trunk=false:axis=z stripped_oak_log:is_trunk=false:axis=z stripped_pale_oak_log:is_trunk=false:axis=z stripped_spruce_log:is_trunk=false:axis=z
method=overlay_fixed
tiles=edges
faces=east west
connect=state
layer=translucent
